export const appContainer: string;
export const innerWindow: string;
export const mapContainer: string;
export const menuButton: string;
export const open: string;
export const title: string;
export const listContainer: string;
export const nav: string;
export const loadingFailed: string;
