export const f1: string;
export const f2: string;
export const f3: string;
export const f4: string;
export const f5: string;
export const f6: string;
export const button: string;
export const hamburgerIcon: string;
export const crossIcon: string;
